services:
  postgres:
    container_name: nestjs-skill-up_db
    image: postgres:17-alpine
    restart: unless-stopped
    networks:
      - nestjs-skill-up_network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT:-5432}:${POSTGRES_CONTAINER_PORT:-5432}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  nestjs-skill-up_network:
    driver: bridge
